/**
 * Golden byte fixtures — the checked-in pin on the on-disk canonical format (`toCanonicalString`),
 * the keystone of "diagrams you can code-review".
 *
 * For every `fixtures/*.nodus.json`, this test asserts two things:
 *   1. restore() accepts it CLEANLY — zero dropped edges, zero migration errors, nothing kept
 *      unmigrated, zero repointed page refs, and zero SerializationIssues. (A fixture that tripped
 *      repair would pin the *repaired* bytes, which is the wrong contract.)
 *   2. Re-serializing the restored records reproduces the file's bytes EXACTLY.
 *
 * Because it compares against bytes on disk (not an in-memory round-trip), it catches ANY
 * byte-affecting change to serialization — key order, number formatting, record sort order, field
 * omission — on every PR, regardless of which paths the PR touched. That is exactly the guarantee an
 * in-memory idempotency test (canonical.test.ts) cannot give.
 *
 * The fixtures are generated by `scripts/gen-fixtures.ts`; regeneration is deliberate. If a change
 * here is intended, run `pnpm exec tsx scripts/gen-fixtures.ts`, review the diff, and ship it with a
 * changeset — a byte change is a semver-BREAKING change to the serialization contract.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { restore, serializeRecords, toCanonicalString, type RestoreOptions, type Snapshot } from '../index.js';

/** The SerializationIssue shape, recovered from the public onError callback (not exported by name). */
type Issue = Parameters<NonNullable<RestoreOptions['onError']>>[0];

const FIXTURES_DIR = fileURLToPath(new URL('./fixtures/', import.meta.url));

/**
 * The fixtures this suite pins, each paired with what it exists to guard. Kept explicit (not derived
 * from the directory) so an added file without a matching entry — or a deleted fixture — fails the
 * roster check below rather than silently losing coverage.
 */
const FIXTURES: ReadonlyArray<{ file: string; guards: string }> = [
  { file: '01-minimal-envelope.nodus.json', guards: 'the empty-document envelope (records:[] branch)' },
  { file: '02-all-record-kinds.nodus.json', guards: 'every record kind + a fully-populated node' },
  { file: '03-pages-membership.nodus.json', guards: 'multi-page pageId membership + parentId' },
  { file: '04-type-versions.nodus.json', guards: 'the typeVersions envelope block (sorted keys)' },
  { file: '05-flow.nodus.json', guards: 'per-edge FlowSpec/FlowScale incl. ordered color stops' },
  { file: '06-unicode-labels.nodus.json', guards: 'unicode labels + non-ASCII code-unit key ordering' },
  { file: '07-number-normalization.nodus.json', guards: 'canonical number coercion (-0, 1e21, 1e-7, rounding)' },
];

describe('golden byte fixtures', () => {
  it('the on-disk roster matches the pinned set (no untested or missing fixture)', () => {
    const onDisk = readdirSync(FIXTURES_DIR)
      .filter((f) => f.endsWith('.nodus.json'))
      .sort();
    const expected = FIXTURES.map((f) => f.file).sort();
    expect(onDisk).toEqual(expected);
  });

  for (const { file, guards } of FIXTURES) {
    describe(file, () => {
      const bytes = readFileSync(`${FIXTURES_DIR}${file}`, 'utf8');
      const snap = JSON.parse(bytes) as Snapshot;
      const issues: Issue[] = [];
      const result = restore(snap, { onError: (i) => issues.push(i) });

      it(`restores cleanly — ${guards}`, () => {
        expect(issues).toEqual([]);
        expect(result.droppedEdges).toBe(0);
        expect(result.migrationErrors).toBe(0);
        expect(result.unmigrated).toBe(0);
        expect(result.repointedPageRefs).toBe(0);
      });

      it('re-serializes byte-identically (the pin)', () => {
        const opts = snap.typeVersions ? { typeVersions: snap.typeVersions } : undefined;
        const reserialized = toCanonicalString(serializeRecords(result.records, opts));
        expect(reserialized).toBe(bytes);
      });
    });
  }
});
