/**
 * Convert vendored official SVGs (packages/icons-cloud/svg/<provider>/) into vector packs.
 * Run after dropping the toolkits + curating svg/. Usage: pnpm build:icons
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { ALLOWLIST } from '../packages/icons-cloud/src/allowlist.js';
import { svgToVectorIcon } from '../packages/icons-cloud/src/codegen/svg-to-vector.js';

const ROOT = process.cwd();
const SVG_ROOT = join(ROOT, 'packages', 'icons-cloud', 'svg');
const GEN = join(ROOT, 'packages', 'icons-cloud', 'src', 'generated');
mkdirSync(GEN, { recursive: true });

const packs: Record<string, Record<string, unknown>> = { aws: {}, azure: {}, gcp: {} };
const provenance: Array<Record<string, string>> = [];
const missing: string[] = [];
const warned: string[] = [];

for (const e of ALLOWLIST) {
  const src = join(SVG_ROOT, e.provider, e.file);
  if (!existsSync(src)) { missing.push(`${e.provider}/${e.file}`); continue; }
  const { icon, warnings } = svgToVectorIcon(readFileSync(src, 'utf8'));
  if (e.needsChip) icon.needsChip = true;
  packs[e.provider]![e.name] = icon;
  provenance.push({ name: e.name, provider: e.provider, file: e.file, category: e.category });
  if (warnings.length) warned.push(`${e.name}: ${warnings.join('; ')}`);
}

if (missing.length) {
  console.error(`Missing vendored SVGs (drop toolkits into packages/icons-cloud/svg/):\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

for (const p of ['aws', 'azure', 'gcp'] as const) {
  const body =
    `// GENERATED by scripts/build-icon-packs.ts — do not edit by hand.\n` +
    `import type { VectorIcon } from '@nodus-dev/core';\n` +
    `export const ${p}Pack: Record<string, VectorIcon> = ${JSON.stringify(packs[p])};\n`;
  writeFileSync(join(GEN, `${p}-pack.ts`), body);
}
writeFileSync(join(ROOT, 'packages', 'icons-cloud', 'provenance.json'), JSON.stringify(provenance, null, 2));
if (warned.length) console.warn(`Conversion warnings:\n  ${warned.join('\n  ')}`);
console.log(`Wrote ${provenance.length} icons (aws/azure/gcp).`);
